name: 'redshift'
version: '0.2.3'
config-version: 2

require-dbt-version: [">=0.17.0", "<0.18.0"]

source-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

profile: redshift_package

models:
  redshift:
    base:
      materialized: ephemeral
    introspection:
      materialized: ephemeral
    views:
      materialized: view
